commands:
  housing:
    settings:
      argument:
        - 'settings'
        - 'setting'
    resident:
      argument:
        - 'resident'
        - 'residents'
        - 'residentlist'
        - 'residentslist'
        - 'listresidents'
        - 'listresident'
        - 'addresident'
        - 'addresidents'
        - 'removeresident'
        - 'removeresidents'
#################
#  PERMISSIONS  #
#################
housing.permissions.reload: 'housing.reload'